#如有端口冲突，可指定端口。（默认8080）
server:
  port: 8081
spring:
  # thymleaf settings
  thymleaf:
    # close cache
    cache: false
    # datasource settings
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://localhost:3306/snapdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://localhost:3306/snapdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=US/Pacific
    username: root
    password: root
    # springboot self fastest connection pool
    hikari:
      #name
      pool-name: DateHikariCP
      # min idle connection num
      mininum-idle: 5
      # max idle connection lifetime (default: 10 mins)
      idle-timeout: 1800000
      # max connection num (default: 10)
      maximum-pool-size: 10
      # auto comit of the connections return from connection pool
      auto-commit: true
      # max lifetime (0 represents for immortal, default: 30 mins)
      max-lifetime: 1800000
      # connection timeout (default: 30 s)
      connection-timeout: 30000
      # search sentence for testing availability of connection
      connection-test-query: SELECT 1

  # redis配置
  redis:
    # ip
    host: 192.168.77.138
    # 端口
    port: 6379
    # 默认库
    database: 0
    # 连接超时时间
    timeout: 10000ms
    lettuce:
      pool:
        # 最大连接数
        max-active: 8
        # 最大连接阻塞等待时间，默认-1
        max-wait: 10000ms
        # 最大空闲连接，默认8
        max-idle: 200
        # 最小空闲连接，默认0
        min-idle: 5

  # Mybatis-plus settings
  mybatis-plus:
    # Mapper.xml settings (mapping file)
    mapper-location: classpath*:/mapper/*Mapper.xml
    # Alias of the types of returned data (default: class name)
    type-aliases-package: com.pro.snap.pojo

  # Mybatis-plus sql logging settings (package of functions & interfaces instead of Mapper.xml)
  logging:
    level:
      com.pro.snap.mapping: debug